### ISSUE TITLE
Globally set `pathPrefix`

### ISSUE THREAD

**Issue by dpup** [dpup/protoc-gen-grpc-gateway-ts#14]
Currently if the server requires a `pathPrefix`, for example, if the app is on a different server to the API, then you need to pass it to the service method:

```js
const resp = await Service.Method(req, {pathPrefix: SERVER_HOST})
```

Or some such. 

I'm thinking a better solution could be built in, maybe using React Context. What do you think @seanami

I'm also thinking about exposing other forms of network configuration.

**Comment by dpup** [comment]
Thinking about this more, we don't want to force a dependency on React or some other library. So whatever method we use here needs to be compatible with various frameworks.

That probably implies a global with `set`/`get` methods which can be hooked into.

**Comment by dpup** [comment]
Here's an approach that doesn't require any changes to the generated code:

```ts
const reqCtx = useContext(RequestContext);

const { isPending, isError, data, error } = useQuery({
  queryKey: ['meta_config'],
  queryFn: () => MetaService.ClientConfig({}, reqCtx),
});
```

I still think it'd be nice to avoid passing `reqCtx`. in everywhere.

**Comment by seanami** [comment]
The code that we use in Productable looks something like this (abridged):

```tsx
import { apiRoot } from '../config';

export function useServiceQuery<E extends EndpointMethod>(
  endpoint: E,
  req: EndpointRequest<E>,
  options?: UseServiceQueryOptions<E>,
): UseServiceQueryResult<E> {
  const ctx = useServiceQueryContext();
  return useQuery({
    // Some stuff...
    queryFn: () =>
      endpoint(req, getSessionReq(ctx.session, apiRoot))
      // ...etc.


export function getSessionReq(session: Session | undefined, apiRoot: string): InitReq {
  const baseReq = getBaseReq(apiRoot);
  if (!session || !session.sessionToken) return baseReq;
  return {
    ...baseReq,
    headers: {
      ...baseReq.headers,
      'X-Session-Token': 'bearer ' + session.sessionToken,
    },
  };
}

export function getBaseReq(apiRoot: string): InitReq {
  const headers = {};
  // Some stuff with headers...
  return {
    credentials: 'include',
    headers,
    pathPrefix: apiRoot,
    redirect: 'manual',
  };
}
```

The `useServiceQueryContext` hook is indeed pulling info from `React.Context`. This approach seems to work pretty well, I'm not sure if I'd really want a global setting?

I definitely agree with not adding a hard dependency on React.

One pattern that we could use for this would be something like:

```tsx
import ApplicationService, { getApplicationService } from 'proto-generated-file.ts';

// Call it in the normal way
ApplicationService.Endpoint(req, { pathPrefix: '...', /* other options */ });

// Configure an application service instance with options once:
const ConfiguredApplicationService = getApplicationService({ pathPrefix: '...' });
ConfiguredApplicationService.Endpoint(req); // No second argument accepted? Or at least not required...
```

**Comment by dpup** [comment]
Maybe the `useServiceQuery` pattern could be abstracted in a way that is reusable. It could be in an npm package `react-query-grpc-gateway`.

Something like this:

``js
import { useServiceQuery } from 'react-query-grpc-gateway';

function Component(props) {
  const { isLoading, isError, error, data } = useServiceQuery(ApplicationService.Endpoint, req);
  ...
  ...
}
```

Maybe "globals" could then be specified with a context:

```js
import { ServiceContext } from 'react-query-grpc-gateway';
function App({children}) {
  return (
    <ServiceContext.Provider value={{pathPrefix: SERVER_HOST, defaultHeaders }}>
      {children}
    </ServiceContext.Provider>
  )
}
```

**Comment by dpup** [comment]
I got started on the above idea [here](https://github.com/dpup/react-query-grpc-gateway) and have it working in one of my projects. I think that's the right way to go for now.

**Comment by seanami** [comment]
Finally too the time to read through the https://github.com/dpup/react-query-grpc-gateway repo. Fantastic! This is a great distillation of the pattern that's been useful for us in a way that's generally adoptable.

One thing that it doesn't handle yet that would still be nice to handle is setting `queryKey` so that consumers don't have to care about how to manage query keys (except in edge cases, where it should probably be overridable). But maybe that's fine for now... But if we were to use this at Productable, I'd still end up wrapping these helpers in another helper.

Maybe that's something that I could tackle at the time that I tried switching Productable to using this public repo for the react-query wrappers...

**Comment by dpup** [comment]
That would be great. I'm having a hard time with some of the APIs outside a real world situation. I have two apps, but they're really simple at the moment. Using Productable as a test bed would be great because of the complex relationships.

**Comment by dpup** [comment]
I forgot I hadn't pushed a change which I'd made locally. [This commit](https://github.com/dpup/react-query-grpc-gateway/commit/a663d10da86bb89b7b9902f970aa96294564dd72) adds a super basic default queryKey. Making it customizable seems like a cool idea, but not yet sure how that should work.
